/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface JwtAuthenticationResponseDto
 */
export interface JwtAuthenticationResponseDto {
    /**
     * 
     * @type {string}
     * @memberof JwtAuthenticationResponseDto
     */
    accessToken?: any;
    /**
     * 
     * @type {string}
     * @memberof JwtAuthenticationResponseDto
     */
    tokenType?: any;
    /**
     * 
     * @type {string}
     * @memberof JwtAuthenticationResponseDto
     */
    role?: any;
}
